namespace: gabriel
# Num desired pods
replicaCount: 1

image:
  repository: acrinterview.azurecr.io/simple-web
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: ""
      paths:
        - path: /gabriel
          pathType: Prefix

# Resource requests and limits application pods
resources:
  limits:
    cpu: 100m      # Maximum CPU the pod can use
    memory: 128Mi  # Maximum Memory the pod can use
  requests:
    cpu: 100m      # Guaranteed minimum CPU
    memory: 128Mi  # Guaranteed minimum Memory

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http