apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "simple-web.fullname" . }}-keda
  namespace: gabriel
spec:
  scaleTargetRef:
    name: {{ include "simple-web.fullname" . }}
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
    - type: cpu
      metadata:
        type: Utilization
        value: "50"
    - type: memory
      metadata:
        type: Utilization
        value: "50"
    - type: cron
      metadata:
        timezone: "Asia/Jerusalem"
        start: "0 8 * * *"
        end: "0 0 * * *"
        desiredReplicas: "1" 